### ISSUE TITLE
Disable Info-Message in Log if homeegram state changes

### ISSUE THREAD

**Issue by Seraphis411** [Apollon77/ioBroker.homee#12] opened 2018-10-14 17:30 UTC
Seems like every time a homeegram gets played by homee (indicator .playing = true) the following message gets printed to the iobroker-log:

`initialize 1 homeegrams`

Could you reconfigure this message to a higher loglevel? For normal use it isn't a necessary information.

**Comment by Apollon77** [comment] 2018-10-14 20:43
WIll be done as soon as I have time ... duplicate of #9

**Closed by Apollon77** 2018-10-14 20:43 UTC
